#!/bin/tcsh
set OKstatus="OK"
if (`caget -t FB_A:use_RF` != 'RF On') then
  echo "Error"
else
  echo "OK"
endif
caget FB_A:isolate_en
caget FB_A:disp_optics
caget FB_A:BPM:use:x_1
caget FB_A:BPM:use:x_2
caget FB_A:BPM:use:x_3
caget FB_A:BPM:use:x_4
caget FB_A:BPM:use:x_5
caget FB_A:BPM:use:x_6
caget FB_A:BPM:use:x_7
caget FB_A:BPM:use:x_8
caget FB_A:BPM:use:y_1
caget FB_A:BPM:use:y_2
caget FB_A:BPM:use:y_3
caget FB_A:BPM:use:y_4
caget FB_A:BPM:use:y_5
caget FB_A:BPM:use:y_6
caget FB_A:BPM:use:y_7
caget FB_A:BPM:use:y_8
caget FB_A:BPM:use_energy:x_1
caget FB_A:BPM:use_energy:x_2
caget FB_A:BPM:use_energy:x_3
caget FB_A:BPM:use_energy:x_4
caget FB_A:BPM:use_energy:x_5
caget FB_A:BPM:use_energy:x_6
caget FB_A:BPM:use_energy:x_7
caget FB_A:BPM:use_energy:x_8
caget FB_A:BPM:use_energy:y_1
caget FB_A:BPM:use_energy:y_2
caget FB_A:BPM:use_energy:y_3
caget FB_A:BPM:use_energy:y_4
caget FB_A:BPM:use_energy:y_5
caget FB_A:BPM:use_energy:y_6
caget FB_A:BPM:use_energy:y_7
caget FB_A:BPM:use_energy:y_8

caget FB_A:use_RF
caget FB_A:disp_optics
caget FB_A:BPM:use_disp:x_1
caget FB_A:BPM:use_disp:x_2
caget FB_A:BPM:use_disp:x_3
caget FB_A:BPM:use_disp:x_4
caget FB_A:BPM:use_disp:x_5
caget FB_A:BPM:use_disp:x_6
caget FB_A:BPM:use_disp:x_7
caget FB_A:BPM:use_disp:x_8
caget FB_A:BPM:use_disp:y_1
caget FB_A:BPM:use_disp:y_2
caget FB_A:BPM:use_disp:y_3
caget FB_A:BPM:use_disp:y_4
caget FB_A:BPM:use_disp:y_5
caget FB_A:BPM:use_disp:y_6
caget FB_A:BPM:use_disp:y_7
caget FB_A:BPM:use_disp:y_8
caget FB_A:BPM:use_en_disp:x_1
caget FB_A:BPM:use_en_disp:x_2
caget FB_A:BPM:use_en_disp:x_3
caget FB_A:BPM:use_en_disp:x_4
caget FB_A:BPM:use_en_disp:x_5
caget FB_A:BPM:use_en_disp:x_6
caget FB_A:BPM:use_en_disp:x_7
caget FB_A:BPM:use_en_disp:x_8
caget FB_A:BPM:use_en_disp:y_1
caget FB_A:BPM:use_en_disp:y_2
caget FB_A:BPM:use_en_disp:y_3
caget FB_A:BPM:use_en_disp:y_4
caget FB_A:BPM:use_en_disp:y_5
caget FB_A:BPM:use_en_disp:y_6
caget FB_A:BPM:use_en_disp:y_7
caget FB_A:BPM:use_en_disp:y_8
